// Posts
export const POST_LIST_REQUEST = 'POST_LIST_REQUEST';
export const POST_LIST_SUCCESS = 'POST_LIST_SUCCESS';
export const POST_LIST_FAIL = 'POST_LIST_FAIL';

export const POST_DETAIL_REQUEST = 'POST_DETAIL_REQUEST';
export const POST_DETAIL_SUCCESS = 'POST_DETAIL_SUCCESS';
export const POST_DETAIL_FAIL = 'POST_DETAIL_FAIL';

export const POST_CATEGORY_REQUEST = 'POST_CATEGORY_REQUEST';
export const POST_CATEGORY_SUCCESS = 'POST_CATEGORY_SUCCESS';
export const POST_CATEGORY_FAIL = 'POST_CATEGORY_FAIL';

export const POST_CREATE_REQUEST = 'POST_CREATE_REQUEST';
export const POST_CREATE_SUCCESS = 'POST_CREATE_SUCCESS';
export const POST_CREATE_FAIL = 'POST_CREATE_FAIL';
export const POST_CREATE_RESET = 'POST_CREATE_RESET';

export const POST_EDIT_REQUEST = 'POST_EDIT_REQUEST';
export const POST_EDIT_SUCCESS = 'POST_EDIT_SUCCESS';
export const POST_EDIT_FAIL = 'POST_EDIT_FAIL';
export const POST_EDIT_RESET = 'POST_EDIT_RESET';

export const POST_DELETE_REQUEST = 'POST_DELETE_REQUEST';
export const POST_DELETE_SUCCESS = 'POST_DELETE_SUCCESS';
export const POST_DELETE_FAIL = 'POST_DELETE_FAIL';

// Images
export const IMAGE_LIST_REQUEST = 'IMAGE_LIST_REQUEST';
export const IMAGE_LIST_SUCCESS = 'IMAGE_LIST_SUCCESS';
export const IMAGE_LIST_FAIL = 'IMAGE_LIST_FAIL';

export const IMAGE_CATEGORY_REQUEST = 'IMAGE_CATEGORY_REQUEST';
export const IMAGE_CATEGORY_SUCCESS = 'IMAGE_CATEGORY_SUCCESS';
export const IMAGE_CATEGORY_FAIL = 'IMAGE_CATEGORY_FAIL';

export const IMAGE_CREATE_REQUEST = 'IMAGE_CREATE_REQUEST';
export const IMAGE_CREATE_SUCCESS = 'IMAGE_CREATE_SUCCESS';
export const IMAGE_CREATE_FAIL = 'IMAGE_CREATE_FAIL';
export const IMAGE_CREATE_RESET = 'IMAGE_CREATE_RESET';

export const IMAGE_DELETE_REQUEST = 'IMAGE_DELETE_REQUEST';
export const IMAGE_DELETE_SUCCESS = 'IMAGE_DELETE_SUCCESS';
export const IMAGE_DELETE_FAIL = 'IMAGE_DELETE_FAIL';
